### ISSUE TITLE
Don't use log.Fatal

### ISSUE THREAD

**Issue by burdiyan** [textileio/go-threads#233]
I've seen that in many places (e.g. in `store` package) the package-global logger is used calling its `Fatal` method.

Fatal calls os.Exit after printing the log and it may break the user's application in a very ugly way. Deferred statements are not executing after calling os.Exit, so it's basically like force-killing the app, which is a lot less than ideal.

Even if something fatal happened within go-threads library, it shouldn't take assumptions about the overall app that uses the library, and it should allow the app to gracefully shut down. IMHO.

The last [Go proverb](https://go-proverbs.github.io) says "Don't panic", but I think it should be applied to os.Exit as well, if not more. You can recover panic, but not os.Exit.

**Comment by sanderpick** [comment]
Those cases of `log.Fatal` are used to indicate something really bad happened that should be considered a bug in the threads library. For example, a transactional guarantee failed, etc. These are cases that _cannot_ be recovered from, in the sense that all bets are off moving forward. The best thing to do is tell the user ASAP so they can make a bug report.

**Comment by burdiyan** [comment]
@sanderpick That makes sense! I understand that this is something Threads can't recover from. But don't you think that panic in this case would be better than os.Exit? At least this would give a chance to the user's app to shutdown properly.

**Comment by jsign** [comment]
Well, this discussion it's complex (and interesting!). 
I like Go provers and are great advice, but such general advice lacks of context.

There's even more general advice: fail fast if something should never happen since break app assumptions. Which assumptions are made? Well, you can be right that Threads is getting into your way if you know that any kind of unexpected error won't break your assumptions, but that might not be the case for other apps. The safest approach is to stop all things.

When you mention _give a chance to the user's app to shutdown properly_, it may mean giving the chance to keep a corrupting state since we can't make any assumptions that they won't still rely on corrupted data while _shutdown properly_. But yes, that's a kind of opinionated and conservative POV. e.g: if you were using a financial lib that detects some negative balance, it might consider that something really bad happened and any kind of logic that might try to shut down properly might cause even more harm since it's relying on the totally unexpected world state.

Of course, all these claims are debatable since we can think of libs and apps that might consider that situation as an error and not an assumption.

Here's when talking about concrete cases helps a lot. There's a high chance that many fatal things could eventually fail in some non-fatal ways with extra thought and some in logic.

**Comment by burdiyan** [comment]
@jsign Thanks for your detailed response. I agree that it's a highly debatable topic, and there's no silver bullet (as always :)).

I still do think that `panic` in this case would be a better solution, but probably that's just a personal preference, probably I'm just heavily biased about the importance of graceful shutdowns. 

Knowing that it was a deliberate decision and not an oversight is helpful though, so thank you 👍
