### ISSUE TITLE
Need help on adding/pinning file on IPFS through threads

### ISSUE THREAD

**Issue by shc261392** [textileio/go-threads#257]
I'm trying to create a service that has similar functionality as [go-foldersync](https://github.com/textileio/go-foldersync). Specifically, I would like to be able to add/get files from the IPFS-lite node the Thread daemon runs on and pinning files with the CIDs.

My service will manage files on the IPFS node, and manage the CIDs and other metadata in a store on Threads.

Since I'm coding in another language other than Go, I used the gRPC API for language binding. However, the API seems limited (I can't find anything that could let me interact with the IPFS-lite node). [js-foldersync](https://github.com/textileio/js-foldersync) seems incomplete in this part, too.

Currently, I'm thinking of a few approaches:

1. Run a full IPFS node one the same machine, and use the IPFS HTTP API to access it. 

2. Access the IPFS-lite node which is run by the Threads daemon by other means (use Go as in go-foldersync, etc.)

I need suggestions on the approaches. Which one sounds like a more viable approach for you? Or did I overlooked something? I'm still trying to understand how Threads V2 works, so please let me know if I misunderstood anything.

**Comment by carsonfarmer** [comment]
Hi @shc261392, thanks for digging into threads! What language _are_ you accessing the gRPC APIs from? Additionally, are you working with relatively large (and raw) files?

**Comment by shc261392** [comment]
I'm accessing the gRPC APIs via Python.

And yes, we are working with relatively large files like images or videos.

**Comment by carsonfarmer** [comment]
So either of your suggested approaches would work. As you are working in go, your second option is ideal, because you can pass the same IPFS-lite node that you use to add files to IPFS to threads, that way you don't have to run two. Having said that, IPFS-lite _doesn't_ really do pinning as in a full IPFS peer, so you'll still want to make sure your data is pinned somewhere if you need long-term persistence. If that is something you need, you could use a pinning service, or run a full IPFS node.

**Comment by shc261392** [comment]
Since file pinning is necessary in our case, I'm sticking to the first approach for now.

Thank you very much for your suggestion.

**Comment by carsonfarmer** [comment]
Thanks for reporting back! Very useful to know various uses and use cases.
