### ISSUE TITLE
Retain connections with net peers

### ISSUE THREAD

**Issue by sanderpick** [textileio/go-threads#276]
Currently, a new connection is created every time a `net` dial is needed. We should maintain a map of host connection.

**Comment by requilence** [comment]
@sanderpick this one looks very critical
- it leaks goroutines. I had 17k goroutines after 10 hours with 13 threads and `PullInterval = time.Minute * 3` (instead of default 10s).
![Screenshot from 2020-04-29 20-20-52](https://user-images.githubusercontent.com/1025231/80633339-44dcc000-8a61-11ea-9436-d7657aa0464f.png)
- probably it creates a huge overhead as I see a lot of "protocol negotiation took" msgs in the log for the same peers (about 20 per 5min per peer)

**Comment by sanderpick** [comment]
Eek, okay... I'll see what I can do about getting to this today / tomorrow.

**Comment by sanderpick** [comment]
Jumping on this later today...

**Comment by requilence** [comment]
Thanks @sanderpick! Let me know if I can help to stress-test or some other way
